name: httpserver
description: Sample HTTP clients and servers
homepage: https://dart.dev/tutorials/server/httpserver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  test: ^1.0.0
  pedantic: ^1.0.0
